version: '3.8'

services:
  habesha_chatbot_api:
    container_name: 2000Habesha
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./chatbot:/app/chatbot:rw
    restart: always
  